### ISSUE TITLE
Traits include yaml file

### ISSUE THREAD

**Issue by briviere** [mulesoft/raml-jaxrs-codegen#38]
I'm trying to include a yaml definition of my traits as follows:

traits: !include CommonTraits.yaml

The codegen keeps telling me it is an invalid raml 

[ERROR] Failed to execute goal org.raml.plugins:raml-jaxrs-maven-plugin:1.0-SNAPSHOT:generate (default) on project raml-jaxrs-jersey-example: Error generating Java classes from: c:\users\rivieb2\raml-jaxrs-codegen\jersey-example\src\main\resources\raml\CommonTraits.yaml: Invalid RAML definition:
[ERROR] -1 Invalid RAML

**Comment by safaci2000** [comment]
+1  I'm having the same issue.  I tried using both directory and sourcePaths with the same results.

**Comment by usarid** [comment]
This repo is no longer being maintained -- check out [the new version](https://github.com/mulesoft/raml-for-jax-rs) please.
